// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { AccountId32 } from "dedot/codecs";
import type {
  GenericContractEvents,
  GenericContractEvent,
} from "dedot/contracts";

export interface ContractEvents<ChainApi extends GenericSubstrateApi>
  extends GenericContractEvents<ChainApi> {
  /**
   *
   * @signature_topic: 0x26fc0ff4d697e1f1c1bdc77783bd95f72093ee851200b3dd5d99526864cb58a1
   **/
  ChannelCreated: GenericContractEvent<
    "ChannelCreated",
    {
      /**
       *
       * @indexed: false
       **/
      channelId: number;
      /**
       *
       * @indexed: false
       **/
      owner: AccountId32;
    }
  >;

  /**
   *
   * @signature_topic: 0x77da7011fb252307bcb5b8052fd393176f45f18c95bc0c82cde50e93fef51bda
   **/
  ChannelUpdated: GenericContractEvent<
    "ChannelUpdated",
    {
      /**
       *
       * @indexed: false
       **/
      channelId: number;
      /**
       *
       * @indexed: false
       **/
      owner: AccountId32;
    }
  >;

  /**
   *
   * @signature_topic: 0xc80793ded29cad43dc36859556ac43571057d15dccdd7f7f178674f8da3211f8
   **/
  MessageSent: GenericContractEvent<
    "MessageSent",
    {
      /**
       *
       * @indexed: false
       **/
      channelId: number;
      /**
       *
       * @indexed: false
       **/
      messageId: number;
    }
  >;

  /**
   *
   * @signature_topic: 0x603725ff61bb1882969c519563f5371302165aeb672ceb6a84ea00b204ed9cbd
   **/
  RequestSent: GenericContractEvent<
    "RequestSent",
    {
      /**
       *
       * @indexed: false
       **/
      channelId: number;
      /**
       *
       * @indexed: false
       **/
      sender: AccountId32;
    }
  >;

  /**
   *
   * @signature_topic: 0x9592099e6b080820b8aafc02157b853cddcdd32ca7fdf126ce0ea384daca25c8
   **/
  RequestCancelled: GenericContractEvent<
    "RequestCancelled",
    {
      /**
       *
       * @indexed: false
       **/
      channelId: number;
      /**
       *
       * @indexed: false
       **/
      sender: AccountId32;
    }
  >;

  /**
   *
   * @signature_topic: 0x192191c238a2a4bff47c910c7ed90757b9ab24ce80b1ca17927dd5c0e410cabd
   **/
  MessageDeleted: GenericContractEvent<
    "MessageDeleted",
    {
      /**
       *
       * @indexed: false
       **/
      channelId: number;
      /**
       *
       * @indexed: false
       **/
      messageId: number;
    }
  >;

  /**
   *
   * @signature_topic: 0x88ccce0b286c7bdf7d2133acf29ae3033b15520d18529a022d871c70b4faba3f
   **/
  ApprovalSubmitted: GenericContractEvent<
    "ApprovalSubmitted",
    {
      /**
       *
       * @indexed: false
       **/
      channelId: number;
      /**
       *
       * @indexed: false
       **/
      approved: Array<number>;
      /**
       *
       * @indexed: false
       **/
      rejected: Array<number>;
    }
  >;

  /**
   *
   * @signature_topic: 0xccb234234021e85698c08f68868b1cc09615107a3f213800cfe21b204aed9a1b
   **/
  MemberLeft: GenericContractEvent<
    "MemberLeft",
    {
      /**
       *
       * @indexed: false
       **/
      channelId: number;
      /**
       *
       * @indexed: false
       **/
      accountId: AccountId32;
    }
  >;
}
